CREATE DATABASE IF NOT EXISTS gestion_operativa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gestion_operativa;

CREATE TABLE IF NOT EXISTS tbl_dotacion (
    id_dotacion INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    nombre_completo VARCHAR(255) NOT NULL,
    usuario_login VARCHAR(100) DEFAULT NULL,
    supervisor_asignado VARCHAR(255) DEFAULT NULL,
    estado_dotacion VARCHAR(60) NOT NULL DEFAULT 'Activo',
    contrato_desde DATETIME DEFAULT NULL,
    contrato_hasta DATETIME DEFAULT NULL,
    tipo_contrato VARCHAR(120) DEFAULT NULL,
    jornada VARCHAR(50) DEFAULT NULL,
    modalidad VARCHAR(120) DEFAULT NULL,
    call_center VARCHAR(120) DEFAULT NULL,
    servicio VARCHAR(255) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    hoja_origen VARCHAR(100) DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_rut (rut),
    KEY idx_tbl_dotacion_estado (estado_dotacion),
    KEY idx_tbl_dotacion_supervisor (supervisor_asignado),
    KEY idx_tbl_dotacion_usuario (usuario_login),
    KEY idx_tbl_dotacion_jefatura (jefatura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_fusion (
    id_fusion INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) DEFAULT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(120) DEFAULT NULL,
    apellido_materno VARCHAR(120) DEFAULT NULL,
    nombre_1 VARCHAR(120) DEFAULT NULL,
    nombre_2 VARCHAR(120) DEFAULT NULL,
    servicio VARCHAR(255) DEFAULT NULL,
    servicio_actual VARCHAR(255) DEFAULT NULL,
    contrato_desde DATETIME DEFAULT NULL,
    contrato_hasta DATETIME DEFAULT NULL,
    tipo_contrato VARCHAR(120) DEFAULT NULL,
    jornada VARCHAR(50) DEFAULT NULL,
    usuario_supervisor VARCHAR(100) DEFAULT NULL,
    usuario_administrador VARCHAR(100) DEFAULT NULL,
    estado_excel VARCHAR(255) DEFAULT NULL,
    modalidad VARCHAR(120) DEFAULT NULL,
    call_center VARCHAR(120) DEFAULT NULL,
    eat_a_observar VARCHAR(255) DEFAULT NULL,
    rut_supervisor VARCHAR(20) DEFAULT NULL,
    supervisor VARCHAR(255) DEFAULT NULL,
    rut_jefatura VARCHAR(20) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    plataforma VARCHAR(120) DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_fusion_rut (rut),
    KEY idx_tbl_dotacion_fusion_supervisor (supervisor),
    KEY idx_tbl_dotacion_fusion_jefatura (jefatura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_fuera_falta_grave (
    id_fuera_falta_grave INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) DEFAULT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(120) DEFAULT NULL,
    apellido_materno VARCHAR(120) DEFAULT NULL,
    nombre_1 VARCHAR(120) DEFAULT NULL,
    nombre_2 VARCHAR(120) DEFAULT NULL,
    servicio VARCHAR(255) DEFAULT NULL,
    servicio_actual VARCHAR(255) DEFAULT NULL,
    contrato_desde DATETIME DEFAULT NULL,
    contrato_hasta DATETIME DEFAULT NULL,
    tipo_contrato VARCHAR(120) DEFAULT NULL,
    jornada VARCHAR(50) DEFAULT NULL,
    usuario_supervisor VARCHAR(100) DEFAULT NULL,
    usuario_administrador VARCHAR(100) DEFAULT NULL,
    estado_excel VARCHAR(255) DEFAULT NULL,
    modalidad VARCHAR(120) DEFAULT NULL,
    call_center VARCHAR(120) DEFAULT NULL,
    eat_a_observar VARCHAR(255) DEFAULT NULL,
    rut_supervisor VARCHAR(20) DEFAULT NULL,
    supervisor VARCHAR(255) DEFAULT NULL,
    rut_administrador VARCHAR(20) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_ffg_rut (rut),
    KEY idx_tbl_dotacion_ffg_supervisor (supervisor),
    KEY idx_tbl_dotacion_ffg_jefatura (jefatura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_renuncias_termino (
    id_renuncia INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) DEFAULT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(120) DEFAULT NULL,
    apellido_materno VARCHAR(120) DEFAULT NULL,
    nombre_1 VARCHAR(120) DEFAULT NULL,
    nombre_2 VARCHAR(120) DEFAULT NULL,
    servicio VARCHAR(255) DEFAULT NULL,
    servicio_actual VARCHAR(255) DEFAULT NULL,
    contrato_desde DATETIME DEFAULT NULL,
    contrato_hasta DATETIME DEFAULT NULL,
    tipo_contrato VARCHAR(120) DEFAULT NULL,
    jornada VARCHAR(50) DEFAULT NULL,
    usuario_supervisor VARCHAR(100) DEFAULT NULL,
    usuario_administrador VARCHAR(100) DEFAULT NULL,
    estado_excel VARCHAR(255) DEFAULT NULL,
    modalidad VARCHAR(120) DEFAULT NULL,
    call_center VARCHAR(120) DEFAULT NULL,
    eat_a_observar VARCHAR(255) DEFAULT NULL,
    rut_supervisor VARCHAR(20) DEFAULT NULL,
    supervisor VARCHAR(255) DEFAULT NULL,
    rut_administrador VARCHAR(20) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_rt_rut (rut),
    KEY idx_tbl_dotacion_rt_supervisor (supervisor),
    KEY idx_tbl_dotacion_rt_jefatura (jefatura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_apoyos_licencias (
    id_apoyo_licencia INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    usuario VARCHAR(100) DEFAULT NULL,
    nombre VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(120) DEFAULT NULL,
    apellido_materno VARCHAR(120) DEFAULT NULL,
    nombre_1 VARCHAR(120) DEFAULT NULL,
    nombre_2 VARCHAR(120) DEFAULT NULL,
    servicio VARCHAR(255) DEFAULT NULL,
    servicio_actual VARCHAR(255) DEFAULT NULL,
    contrato_desde DATETIME DEFAULT NULL,
    contrato_hasta DATETIME DEFAULT NULL,
    tipo_contrato VARCHAR(120) DEFAULT NULL,
    jornada VARCHAR(50) DEFAULT NULL,
    usuario_supervisor VARCHAR(100) DEFAULT NULL,
    usuario_administrador VARCHAR(100) DEFAULT NULL,
    estado_excel VARCHAR(255) DEFAULT NULL,
    modalidad VARCHAR(120) DEFAULT NULL,
    call_center VARCHAR(120) DEFAULT NULL,
    eat_a_observar VARCHAR(255) DEFAULT NULL,
    rut_supervisor VARCHAR(20) DEFAULT NULL,
    supervisor VARCHAR(255) DEFAULT NULL,
    rut_administrador VARCHAR(20) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    plataforma VARCHAR(120) DEFAULT NULL,
    fecha_hoja DATETIME DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_al_rut (rut),
    KEY idx_tbl_dotacion_al_supervisor (supervisor),
    KEY idx_tbl_dotacion_al_jefatura (jefatura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_jefatura (
    id_jefatura INT AUTO_INCREMENT PRIMARY KEY,
    supervisor VARCHAR(255) NOT NULL,
    usuario_supervisor VARCHAR(100) DEFAULT NULL,
    usuario_administrador VARCHAR(100) DEFAULT NULL,
    rut_supervisor VARCHAR(20) NOT NULL,
    rut_administrador VARCHAR(20) DEFAULT NULL,
    jefatura VARCHAR(255) DEFAULT NULL,
    estado VARCHAR(60) DEFAULT NULL,
    contrato VARCHAR(120) DEFAULT NULL,
    anidamiento VARCHAR(255) DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tbl_dotacion_jefatura_rut_supervisor (rut_supervisor),
    KEY idx_tbl_dotacion_jefatura_jefatura (jefatura),
    KEY idx_tbl_dotacion_jefatura_estado (estado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tbl_dotacion_import_log (
    id_importacion INT AUTO_INCREMENT PRIMARY KEY,
    archivo_nombre VARCHAR(255) NOT NULL,
    hoja_nombre VARCHAR(100) NOT NULL,
    tabla_destino VARCHAR(100) NOT NULL,
    registros_procesados INT NOT NULL DEFAULT 0,
    registros_insertados INT NOT NULL DEFAULT 0,
    registros_actualizados INT NOT NULL DEFAULT 0,
    observacion TEXT DEFAULT NULL,
    fecha_importacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_tbl_dotacion_import_log_fecha (fecha_importacion),
    KEY idx_tbl_dotacion_import_log_hoja (hoja_nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP VIEW IF EXISTS vw_dotacion_consolidada;
CREATE VIEW vw_dotacion_consolidada AS
SELECT
    d.rut,
    d.nombre_completo,
    d.usuario_login,
    d.supervisor_asignado,
    d.estado_dotacion,
    d.contrato_desde,
    d.contrato_hasta,
    d.tipo_contrato,
    d.jornada,
    d.modalidad,
    d.call_center,
    d.servicio,
    d.jefatura,
    d.hoja_origen,
    d.fecha_importacion,
    d.fecha_actualizacion
FROM tbl_dotacion d;
